import express from 'express'
import { conf } from '@clubgo/util'
import * as bodyParser from 'body-parser'
import * as cookieParser from 'cookie-parser'
import crypto from 'crypto'
import vhost from 'vhost'

/**
 * @description
 * Welcome to the ClubGo Backend API Server
 * This server routes and serves all the data in the website
 * The API exposes all the available funcionality
 * 
 * @author
 * * Alisamar Husain | zrthxn
 * 
 * @copyright 2019
 * Copyright Alisamar Husain
 * 
 * @license MIT
 * This software is provided as-is with no
 * warranties or guatantees.
 */

export const _Server = express()
export default _Server
// All Express instances starting with an underscore,
// like _Server, _Router are global routing objects.

_Server.use(cookieParser())
_Server.use(bodyParser.json())
_Server.use(bodyParser.urlencoded({ extended: true }))
_Server.use(express.json())
_Server.use(express.urlencoded({ extended: true }))

import APIRouter from './Routes/APIRouter'
import WebRouter from './Routes/WebRouter'

import { APIEndpoints } from '@clubgo/features/api'
// import {  }
const ServerConfig = require('./serverconfig.json')

// MongoDB Connection
import { DatabaseConnection } from '@clubgo/database'
const db = new DatabaseConnection({ database: 'clubgo' })
// ========================================================

/**
 * `----` : Flow is continued
 * `====` : Flow is broken
 * `STOP` : Flow goes no further in this direction
 */

/**
 * @description Server CORS policy. 
 * Handles all preflight requests 
 */
_Server.use((req, res, next)=>{
  if(ServerConfig.policy.ALLOW_CORS)
    res.header('Access-Control-Allow-Origin', ServerConfig.policy.ALLOW_ORIGIN)
  res.header('Access-Control-Allow-Headers', ServerConfig.policy.ALLOW_HEADERS)
  res.header('Access-Control-Allow-Methods', ServerConfig.policy.ALLOW_METHODS)
  next()
})

// Security Lifecycle Routes
// --------------------------------------------------------
// 1. Authenticate service, CSRF 
const AuthRouter = express.Router()
AuthRouter.post('/_authenticate', (req, res)=>{
  // NOT REAL KEYS
  const APIKEY = 'qWertT2uiOp2lkjhgfD5Sa2zxcvBn831'
  const SECRET = 'edcyTG6hg7ETGutghyrYHFLII7HCyjfh5yjYJKGHfyt7srDJ67jf78khvr' // later generated by algo
  
  const { shared } = req.body
  
  // Set unique CSRF Tokens
  // 1. you send the shared apiKey
  // 2. I use the current apiSecret to generate CSRF access token
  // -- accessToken = sha512( apiKey + '\\' + apiSecret ).digest(base64)
  // 3. I send the access token to you

  // Every 100 transactions the apiSecret is changed

  const token = crypto.createHmac('sha512', APIKEY).update(SECRET).digest('base64')
  
  if(shared===APIKEY) 
    res.send({ token })
  else
    res.sendStatus(403)
})

// 2. API Login or user login 
const LoginRouter = express.Router()
LoginRouter.post('/_login', (req, res)=>{
  // Check CSRF Tokens
  // Set proper and unique login header
  // Set access headers for API access, according to access level
  res.send(':: LOGIN ::')
})

// Router
// --------------------------------------------------------
_Server.use(AuthRouter)

_Server.use(LoginRouter)

// Development
_Server.use(APIRouter)
// _Server.use(WebRouter)

// Production
// _Server.use(vhost(ServerConfig.domains.web, WebRouter))

// _Server.use(vhost(APIEndpoints.api.url, APIRouter))

// STOP ============================================== STOP

_Server.use((req, res)=>{
  // End any caught requests if no matching paths are found
  res.end('Request Forcefully Closed. Your request was caught here but did not match any paths.')
})
